### PR TITLE
Fix automatic warnings on AutoMod-blocked messages for forum channels

### LINKED ISSUE #224: Bug: Running auto-warn filters on AutoMod-blocked messages will fail if AutoMod stops a forum channel post from being created
An AutoMod block like this:
image
...will lead to a failure to warn with exception `System.ArgumentException: GuildForum channels do not support sending text messages.`

### PR DESCRIPTION
**Pull request by FloatingMilkshake**
This PR closes #224. 

Previously when AutoMod would block thread creation in a forum channel (original message matched a filter), Cliptok would catch the AutoMod block and attempt to send its automatic warning message directly into the forum channel—this would fail, because you cannot send a text message into a `GuildForum` channel. Thus the entire warning would fail. This PR adds a configurable fallback channel (`forumChannelAutoWarnFallbackChannel` in config.json) that is used for warning messages where the warning is in response to an AutoMod-blocked message in a `GuildForum` channel.

(Note that for messages inside an already-created thread, the warning message is sent in the thread—those have different channel types, like `PublicThread` and `PrivateThread`.)

### CODE REVIEW

File: Events/MessageEvent.cs [hunk 1]
```diff
@@ -106,8 +106,14 @@ static async Task DeleteAndWarnAsync(DiscordMessage message, string reason, Disc
         
         static async Task DeleteAndWarnAsync(MockDiscordMessage message, string reason, DiscordClient client, bool wasAutoModBlock = false)
         {
+            var channel = message.Channel;
+            
             if (!wasAutoModBlock)
                 _ = message.DeleteAsync();
+            else
+                if (channel.Type is DiscordChannelType.GuildForum)
+                    channel = await client.GetChannelAsync(Program.cfgjson.ForumChannelAutoWarnFallbackChannel);
```
Comment (Erisa) [inline Events/MessageEvent.cs:115]: Is it possible to fetch this once and reference that instance later? We used to have issues where D#+ wouldn't correctly cache `GetChannelAsync` calls and then we'd get rate limited if there's a lot of instances in a short space of time (e.g. raid spam)

**Review by Erisa — APPROVED** [review]

File: Events/MessageEvent.cs (hunk 1 above)
Comment (FloatingMilkshake) [reply Events/MessageEvent.cs:115]: Sure—I could throw it into `Program.cs` and fetch on startup, if that's alright

Comment (Erisa) [reply Events/MessageEvent.cs:115]: Yeah that makes sense

**Review by Erisa — APPROVED** [review]
